[workspace]
members = ["??/??"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
# utils = { path = "../aoc_utils", package = "aoc_utils" }
utils = { git = "https://github.com/remlse/aoc-utils", package = "aoc_utils" }
