[workspace]
members = ["??/??"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
itertools = "0.10"
derive_more = "0.99"
utils = { git = "https://github.com/remlse/aoc-utils.git", package = "aoc_utils" }
