[package]
name = "aoc_19_07"
version.workspace = true
edition.workspace = true

[dependencies]
intcode-computer = { version = "0.1.0", path = "../intcode-computer" }
itertools.workspace = true
utils.workspace = true
