[package]
name = "aoc_15_18"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools.workspace = true
derive_more.workspace = true
utils.workspace = true
