name: test
on: [push]

jobs:
  check_difficulty_spec:
    name: check difficulty spec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hustcer/setup-nu@v3
        with:
          version: 0.78
      - name: check difficulty spec
        run: ./dev/scripts/check_difficulty.nu
  what_to_test:
    name: figure out what to test
    runs-on: ubuntu-latest
    outputs:
      what: ${{ steps.what_to_test.outputs.what }}
    steps:
      - uses: actions/checkout@v3
      - uses: hustcer/setup-nu@v3
        with:
          version: 0.78
      - id: what_to_test
        name: figure out what to test
        run: echo "what=$(./dev/scripts/what_to_test.nu)" >> "$GITHUB_OUTPUT"
  test:
    name: test
    needs:
      - check_difficulty_spec
      - what_to_test
    if: needs.what_to_test.outputs.what != ''
    env:
      WHAT: ${{ needs.what_to_test.outputs.what }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: format
        run: cargo fmt --check $WHAT
      - name: clippy
        run: cargo clippy $WHAT -- -D warnings
      - name: test
        run: cargo test $WHAT
